Description: >
  This template is used to create and deploy a simple VPC with one public and one private subnet and associated gateways
  
Resources: 
  FridayHittVpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: "MH-VPC"
          
  FridayHittPubSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: eu-west-1a
      VpcId: !Ref FridayHittVpc
      CidrBlock: 10.0.0.0/28
      MapPublicIpOnLaunch: true        
      Tags: 
        - Key: Name
          Value: "MH-Public-Subnet"
            
  FridayHittPrvSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-1a
      VpcId: !Ref FridayHittVpc
      CidrBlock: 10.0.1.0/28
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: "MH-Private-Subnet"
            
  FridayHittInetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: FridayHittVpc
    Properties:
      Tags:
        - Key: Name
          Value: "MH-Inet-Gateway"

  AttachInetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FridayHittVpc
      InternetGatewayId: !Ref FridayHittInetGateway
      
  FridayHittElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: "MH-ElasticIP"

  FridayHittNatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId:
        Fn::GetAtt:
        - FridayHittElasticIP
        - AllocationId
      SubnetId: !Ref FridayHittPrvSubnet
      Tags:
        - Key: Name
          Value: "MH-NATGateway"
          
  FridayHittPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref FridayHittVpc
      Tags: 
        - Key: Name
          Value: "MH-PublicRouteTable"

  FridayHittRouteToIGW:
    Type: AWS::EC2::Route
    DependsOn:
      - FridayHittInetGateway
      - AttachInetGateway
    Properties:
      RouteTableId: !Ref FridayHittPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FridayHittInetGateway
              
  FridayHittPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref FridayHittVpc
      Tags:
        - Key: Name
          Value: "MH-PrivateRouteTable"
          
  FridayHittRouteToNAT:
    Type: AWS::EC2::Route
    DependsOn:  FridayHittRouteToIGW
    Properties:
      RouteTableId: !Ref FridayHittPrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref FridayHittNatGateway
      
  PublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref FridayHittPubSubnet
      RouteTableId: !Ref FridayHittPublicRouteTable
      
  PrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
       SubnetId: !Ref FridayHittPrvSubnet
       RouteTableId: !Ref FridayHittPrivateRouteTable
       
    