Description: >
  This template is used to create and deploy a simple VPC with one public and one private subnet and associated gateways
  
Resources: 
  FridayHittVpc:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: "MH-VPC"
          
  FridayHittPubSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: eu-west-1a
      VpcId: !Ref FridayHittVpc
      CidrBlock: 10.0.0.0/28
      MapPublicIpOnLaunch: true        
      Tags: 
        - Key: Name
          Value: "MH-Public-Subnet"
            
  FridayHittPrvSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-1a
      VpcId: !Ref FridayHittVpc
      CidrBlock: 10.0.1.0/28
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: "MH-Private-Subnet"
            
  FridayHittInetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: FridayHittVpc
    Properties:
      Tags:
        - Key: Name
          Value: "MH-Inet-Gateway"

  AttachInetGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref FridayHittVpc
      InternetGatewayId: !Ref FridayHittInetGateway