Description: >
  Template to define 2x EC2 instances and associated security groups
  
Resources:
  PrvEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00385a401487aefa4
      SecurityGroups: [ !Ref PrvSecurityGrp ]
      InstanceType: t2.micro
      
  PrvSecurityGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access via port 80 + SSH
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
        - CidrIp:  0.0.0.0/0 #This should be refined to restricted list
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
 
  PubEC2Instance:
  Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-00385a401487aefa4
      SecurityGroups: [ !Ref PubSecurityGrp ]
      InstanceType: t2.micro
       
  PubSecurityGrp:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupDescription: Enable HTTP access via port 80 + SSH
     SecurityGroupIngress: 
       - CidrIp: 0.0.0.0/0
         IpProtocol: tcp
         FromPort: 80
         ToPort: 80
       - CidrIp:  0.0.0.0/0 #This should be refined to restricted list
         IpProtocol: tcp
         FromPort: 22
         ToPort: 22    